owner: VantaInteractive
repo: Status

sites:
  - name: VI Website
    url: https://vantainteractive.com
  - name: VI API
    url: https://api.vantainteractive.com
  - name: VI Docs
    url: https://docs.vantainteractive.com
  - name: VI Knowledge Base
    url: https://support.vantainteractive.com
  - name: VI Legal
    url: https://legal.vantainteractive.com
  - name: VI Status
    url: https://status.vantainteractive.com
  - name: Vanta Social
    url: https://social.vantainteractive.com

assignees:
  - AlexTECPlayz

skipDeleteIssues: true

status-website:
  cname: status.vantainteractive.com
  logoUrl: https://raw.githubusercontent.com/vantainteractive/vantainteractive.com/main/favicon/vi-logo-big-bk.png
  name: Status 
  themeUrl: https://status.vantainteractive.com/vantadark.css

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"
